export const appImages = {
  splashScreenLogo: require("../../assets/images/splashScreenLogo.png"),
  greeBackground: require("../../assets/images/greenBackground.png"),
  leafLogoWhite: require("../../assets/images/leafLogoWhite.png"),
  leafLogo: require("../../assets/images/leafLogo.png"),
  leafySignInLogo: require("../../assets/images/leafySignInLogo.png"),
  filterLogo: require("../../assets/images/filterLogo.png"),
  bellLogo: require("../../assets/images/bellLogo.png"),
  settingsLogo: require("../../assets/images/settingsLogo.png"),
  heightLogo: require("../../assets/images/heightLogo.png"),
  sunLogo: require("../../assets/images/sunLogo.png"),
  typeLogo: require("../../assets/images/typeLogo.png"),
  waterLogo: require("../../assets/images/waterLogo.png"),
  whishlistLogo: require("../../assets/images/whishlistLogo.png"),
  addCircleLogo: require("../../assets/images/addCircleLogo.png"),
  cameraOutlinedLogo: require("../../assets/images/camaraOutlinedLogo.png"),
  callenderLogo: require("../../assets/images/callenderLogo.png"),
  postLogo: require("../../assets/images/postLogo.png"),
  favouritesLogo: require("../../assets/images/favouritesLogo.png"),
  homeLogo: require("../../assets/images/homeLogo.png"),
  userLogo: require("../../assets/images/userLogo.png"),
};
