export const ReduxLoadingConstants = {
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_INTERNET_CONNECTION: "SET_INTERNET_CONNECTION",
  SET_API_MESSAGE: "SET_API_MESSAGE",
};
export const ReduxProfileConstants = {
  SET_PROFILE: "SET_PROFILE",
};
export const ReduxPlantConstants = {
  SET_DETAILED_PLANT_DATA: "SET_DETAILED_PLANT_DATA",
  SET_ADD_PLANT: "SET_ADD_PLANT",
  SET_PLAT_DATA: "SET_PLAT_DATA",
  SET_FAQPLAT_DATA: "SET_FAQPLAT_DATA",
  SET_MESSAGE: "SET_MESSAGE",
};
export const ReduxHomeConstants = {
  SET_LOCATION: "SET_LOCATION",
  SET_ADDRESS:'SET_ADDRESS',
};
export const ReduxNotificationConstants = {
  SET_ALL_NOTIFICATIONS: "SET_ALL_NOTIFICATIONS",
};
